import './bootstrap';
import './animate.js';
import './change_user_icon';
import './change_numbers_buttons';
import './load_modal_data';
import './add_to_cart';
import './login_handler';
import './payment_delivery_show';
import './edit_product';
